version: "3.8"

services:
  nextjs:
    image: hvssvn78/zenbilling:latest
    container_name: zenbilling_frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true 