version: "3.8"

services:
  nextjs:
    image: hvssvn78/zenbilling:latest
    container_name: zenbilling_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NEXT_PUBLIC_BETTER_AUTH_API_URL=${NEXT_PUBLIC_BETTER_AUTH_API_URL}
    networks:
      - app-network

networks:
  app-network:
    external: true 