version: "3.8"

services:
  nextjs:
    image: hvssvn78/zenbilling:latest
    container_name: zenbilling_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://zenbillingapi.dynamicwebforge.fr/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=zenbilling"
      - "com.docker.compose.service=frontend"

networks:
  app-network:
    external: true 