name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: hvssvn78/zenbilling:latest
                  build-args: |
                    NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
                    JWT_SECRET=${{ secrets.JWT_SECRET }}

            - name: Clean up dangling Docker images
              run: |
                  docker image prune -f

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Create docker-compose.yml with environment variables
              run: |
                cat > docker-compose.yml << 'EOL'
                version: '3'
                services:
                  zenbilling_frontend:
                    image: hvssvn78/zenbilling:latest
                    container_name: zenbilling_frontend
                    restart: always
                    ports:
                      - "3000:3000"
                    environment:
                      - NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
                      - JWT_SECRET=${{ secrets.JWT_SECRET }}
                EOL

            - name: Transfer docker-compose.yml to server
              run: |
                  scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/zenbilling/zenbilling_frontend/docker-compose.yml

            - name: Deploy with Docker Compose
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /zenbilling/zenbilling_frontend && docker compose down && docker compose pull && docker compose up -d"

            - name: Clean up remote dangling Docker images
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker image prune -f"
