name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: hvssvn78/zenbilling:latest

            - name: Clean up dangling Docker images
              run: |
                  docker image prune -f

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Transfer docker-compose.yml to server
              run: |
                  scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/zenbilling/docker-compose.yml

            - name: Deploy with Docker Compose
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
                    cd /zenbilling && \
                    docker-compose down --remove-orphans && \
                    docker system prune -f && \
                    docker network create app-network || true && \
                    docker-compose pull && \
                    COMPOSE_HTTP_TIMEOUT=300 docker-compose up -d --force-recreate
                  '

            - name: Verify deployment
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
                    cd /zenbilling && \
                    docker-compose ps && \
                    docker-compose logs --tail=50
                  '
